### ISSUE TITLE
Bugged character screen after conversion

### ISSUE THREAD

**Issue by OhhLoz** [ArchangelWTF/SPT.ProfileConverter#2]
Hi, Thanks for this tool, super useful & saves having to manually edit the profile up to the same level,

I'm running into an issue with the character screen,
the left side is bugged, with the stats displaying the placeholders, no character model and the clothing dropdowns arent functional.
After opening the screen it disables the top menu from working aswell, so I cant click overall, tasks, achievements etc.

I was wondering if you had any ideas on if/how this could be fixed, thank you

![image](https://github.com/user-attachments/assets/109f053f-6892-4427-b7b7-b3a826c614d5)

**Comment by ArchangelWTF** [comment]
Hey there,

Yes it's to do with that you had a clothing mod in the past, you can fix this by going to SPT_Data/Server/Configs/core.json and setting removeModItemsFromProfile to true, then go back to that screen you took the screenshot in and set your PMC back to the default clothing.

**Comment by OhhLoz** [comment]
Thanks for the response, I did indeed have a clothing mod however only had vanilla clothing equipped and have the same mod installed currently, albeit the 3.8.3 version. 

Worked like a charm thank you, I was worried it would remove all the weapons and stash items added by mods with that label lol
